version: '3.8'

services:
  dev-db:
    image: postgres:14.5
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: STL
    networks:
      - stl

networks:
  stl: