export const ERRORS = {
    USER_NOT_FOUND: "User not found",
    TRAFFIC_LIGHT_NOT_FOUND: "Traffic light not found",
    CROSSROADS_NOT_FOUND: "Crossroads not found",
    MISSED_DATA: "Data is required",
    ADDING_ERROR: "There were something wrong when adding",
    FEED_KEY_NOT_FOUND: "A Feed key is required",
    PUBLIC_ERROR: "There were something wrong when publishing",
    CREATE_NEW_FEED_ERROR: "Cannot create new Feed",
    DELETE_FEED_ERROR: "Cannot delete the feed",
    CREATE_NEW_GROUP_ERROR: "Cannot create new Group",
    DELETE_GROUP_ERROR: "Cannot delete the Group",
    UPDATE_ACTOR_NOT_FOUND: "An user id or crossroads id is required",
    UPDATE_ERROR: "Cannot update",
    REGISTER_ERROR: "Cannot register for new user",
}